ARG CUDA_VERSION="11.8.0"
ARG CUDNN_VERSION="8"
ARG UBUNTU_VERSION="22.04"
ARG DOCKER_FROM=nvidia/cuda:$CUDA_VERSION-cudnn$CUDNN_VERSION-devel-ubuntu$UBUNTU_VERSION

# Base NVidia CUDA Ubuntu image
FROM $DOCKER_FROM AS base

RUN mkdir -p /app
WORKDIR /app

ENV LANG="C.UTF-8"
ENV TZ=Asia/Kolkata \
    DEBIAN_FRONTEND=noninteractive

RUN apt-get update -y && \
    apt-get install -y python3 python3-dev python3-pip python3-venv && \
    apt install build-essential -yq && \
    apt install espeak-ng -yq && \
    apt install cmake -yq && \
    apt install tzdata -yq && \
    apt install -y wget -yq && \
    apt-get clean && \
    apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false && \
    rm -rf /var/lib/apt/lists/*


RUN pip install MarkupSafe==2.1.2 numpy==1.23.3 cython six==1.16.0

ENV PATH="/usr/local/cuda/bin:${PATH}"

# Install pytorch
ARG PYTORCH="2.0.1"
ARG CUDA="118"
RUN pip3 install --no-cache-dir -U torch==$PYTORCH --extra-index-url https://download.pytorch.org/whl/cu$CUDA

COPY requirements.txt /app
RUN pip install -r requirements.txt

COPY . /app

CMD [ "python3", "-u", "handler.py" ]